# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSuccessfulentry():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_successfulentry(self):
    # Test name: successful entry
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://leetcode.com/")
    # 2 | setWindowSize | 1920x1053 | 
    self.driver.set_window_size(1920, 1053)
    # 3 | click | linkText=Create Account | 
    self.driver.find_element(By.LINK_TEXT, "Create Account").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | abir1234
    self.driver.find_element(By.NAME, "username").send_keys("abir1234")
    # 6 | type | name=username | abir123
    self.driver.find_element(By.NAME, "username").send_keys("abir123")
    # 7 | click | name=password1 | 
    self.driver.find_element(By.NAME, "password1").click()
    # 8 | type | name=password1 | abir1234
    self.driver.find_element(By.NAME, "password1").send_keys("abir1234")
    # 9 | click | name=password2 | 
    self.driver.find_element(By.NAME, "password2").click()
    # 10 | type | name=password2 | abir1234
    self.driver.find_element(By.NAME, "password2").send_keys("abir1234")
    # 11 | click | name=email | 
    self.driver.find_element(By.NAME, "email").click()
    # 12 | click | name=email | 
    self.driver.find_element(By.NAME, "email").click()
    # 13 | type | name=email | abir6@gmail.com
    self.driver.find_element(By.NAME, "email").send_keys("abir6@gmail.com")
    # 14 | click | css=.btn-content__2V4r | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-content__2V4r").click()
    # 15 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 16 | type | name=username | abir1235678
    self.driver.find_element(By.NAME, "username").send_keys("abir1235678")
    # 17 | click | name=signup_btn | 
    self.driver.find_element(By.NAME, "signup_btn").click()
    # 18 | assertText | css=p:nth-child(2) | what brought you here?
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2)").text == "what brought you here?"
  
