# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPasswordtooshort():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_passwordtooshort(self):
    # Test name: password too short
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://leetcode.com/")
    # 2 | setWindowSize | 1920x1053 | 
    self.driver.set_window_size(1920, 1053)
    # 3 | click | linkText=Create Account | 
    self.driver.find_element(By.LINK_TEXT, "Create Account").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | test2
    self.driver.find_element(By.NAME, "username").send_keys("test2")
    # 6 | click | name=password1 | 
    self.driver.find_element(By.NAME, "password1").click()
    # 7 | type | name=password1 | abcd1
    self.driver.find_element(By.NAME, "password1").send_keys("abcd1")
    # 8 | mouseDown | name=password2 | 
    element = self.driver.find_element(By.NAME, "password2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 9 | mouseUp | css=.error-message-container__msvN:nth-child(4) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(4)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | css=.form__2-sN | 
    self.driver.find_element(By.CSS_SELECTOR, ".form__2-sN").click()
    # 11 | type | name=password2 | abcd1
    self.driver.find_element(By.NAME, "password2").send_keys("abcd1")
    # 12 | click | name=email | 
    self.driver.find_element(By.NAME, "email").click()
    # 13 | type | name=email | 123456@postgres.com
    self.driver.find_element(By.NAME, "email").send_keys("123456@postgres.com")
    # 14 | click | css=.btn-content-container__2HVS | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-content-container__2HVS").click()
    # 15 | click | css=.error-message-container__msvN:nth-child(4) > .error-message__3Q-C | 
    self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(4) > .error-message__3Q-C").click()
    # 16 | assertText | css=.error-message-container__msvN:nth-child(4) > .error-message__3Q-C | Must be 8 characters or more, needs at least one number and one letter
    assert self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(4) > .error-message__3Q-C").text == "Must be 8 characters or more, needs at least one number and one letter"
  
