# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPasswordsdontmatch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_passwordsdontmatch(self):
    # Test name: passwords dont match
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://leetcode.com/")
    # 2 | setWindowSize | 1920x1053 | 
    self.driver.set_window_size(1920, 1053)
    # 3 | click | linkText=Create Account | 
    self.driver.find_element(By.LINK_TEXT, "Create Account").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | test2
    self.driver.find_element(By.NAME, "username").send_keys("test2")
    # 6 | click | name=password1 | 
    self.driver.find_element(By.NAME, "password1").click()
    # 7 | type | name=password1 | a12345678
    self.driver.find_element(By.NAME, "password1").send_keys("a12345678")
    # 8 | click | name=password2 | 
    self.driver.find_element(By.NAME, "password2").click()
    # 9 | type | name=password2 | 4
    self.driver.find_element(By.NAME, "password2").send_keys("4")
    # 10 | click | name=email | 
    self.driver.find_element(By.NAME, "email").click()
    # 11 | type | name=email | 123456@postgres.com
    self.driver.find_element(By.NAME, "email").send_keys("123456@postgres.com")
    # 12 | click | name=signup_btn | 
    self.driver.find_element(By.NAME, "signup_btn").click()
    # 13 | click | css=.error-message-container__msvN:nth-child(6) > .error-message__3Q-C | 
    self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(6) > .error-message__3Q-C").click()
    # 14 | assertText | css=.error-message-container__msvN:nth-child(6) > .error-message__3Q-C | The passwords you entered do not match.
    assert self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(6) > .error-message__3Q-C").text == "The passwords you entered do not match."
  
