# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsernameshort():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_usernameshort(self):
    # Test name: username short
    # Step # | name | target | value
    # 1 | open | /accounts/signup/ | 
    self.driver.get("https://leetcode.com/accounts/signup/")
    # 2 | setWindowSize | 1920x1053 | 
    self.driver.set_window_size(1920, 1053)
    # 3 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 4 | type | name=username | a
    self.driver.find_element(By.NAME, "username").send_keys("a")
    # 5 | click | name=password1 | 
    self.driver.find_element(By.NAME, "password1").click()
    # 6 | type | name=password1 | a12345678
    self.driver.find_element(By.NAME, "password1").send_keys("a12345678")
    # 7 | click | name=password2 | 
    self.driver.find_element(By.NAME, "password2").click()
    # 8 | type | name=password2 | a12345678
    self.driver.find_element(By.NAME, "password2").send_keys("a12345678")
    # 9 | click | name=email | 
    self.driver.find_element(By.NAME, "email").click()
    # 10 | type | name=email | 123456@postgres.com
    self.driver.find_element(By.NAME, "email").send_keys("123456@postgres.com")
    # 11 | click | css=.btn-content__2V4r | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-content__2V4r").click()
    # 12 | click | css=.error-message-container__msvN:nth-child(2) > .error-message__3Q-C | 
    self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(2) > .error-message__3Q-C").click()
    # 13 | assertText | css=.error-message-container__msvN:nth-child(2) > .error-message__3Q-C | Content is too short
    assert self.driver.find_element(By.CSS_SELECTOR, ".error-message-container__msvN:nth-child(2) > .error-message__3Q-C").text == "Content is too short"
  
